### ISSUE TITLE
defaults to using both MakeMaker, ModuleBuild

### ISSUE THREAD

**Issue by karenetheridge** [HayoBaan/Dist-Zilla-PluginBundle-Author-HAYOBAAN#1]
Can you just use MakeMaker? Module::Build is full of fail and should only be used when EUMM doesn't have the options you need. Many thanks!

**Comment by HayoBaan** [comment]
Hi Karen,
Interesting request. From the documentation & comments I had actually understood Module::Build was supposed to be the preferred build method for the future, I guess not then :open_mouth:
I can easily adapt this of course and probably make the build method an option defaulting to MakeMaker.

Thanks,
Hayo

**Comment by HayoBaan** [comment]
I just uploaded v0.009 that now has the build method configurable.

Thanks for looking into this,
Hayo

**Comment by karenetheridge** [comment]
Re MB being the future.. it was thought to be... and then that didn't happen... more here - http://www.dagolden.com/index.php/2140/paying-respect-to-modulebuild/

**Comment by HayoBaan** [comment]
Ah, that's actually quite an old article, thanks for letting me know!
