### ISSUE TITLE
Dist::Zilla::Plugin::ReadmeAnyFromPod encoding issues.

### ISSUE THREAD

**Issue by schwern** [HayoBaan/Dist-Zilla-PluginBundle-Author-HAYOBAAN#3]
After installing the bundle, I got an error trying to `dzil test` on utf8::all.

```
$ dzil --version
dzil (Dist::Zilla::App) version 6.007 (/Users/schwern/perl5/perlbrew/perls/stable/bin/dzil)

$ dzil test
[DZ] building distribution under .build/tjnNHorSRK for installation
[DZ] beginning to build utf8-all
[@Author::HAYOBAAN/Author::HAYOBAAN::NextVersion] Updating version from 0.019 to 0.020
Subroutine JSON::PP::Boolean::(++ redefined at /Users/schwern/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/overload.pm line 50.
Subroutine JSON::PP::Boolean::(-- redefined at /Users/schwern/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/overload.pm line 50.
Subroutine JSON::PP::Boolean::(0+ redefined at /Users/schwern/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/overload.pm line 50.
[@Author::HAYOBAAN/GitHub::Meta] Getting GitHub repository info
[DZ] guessing dist's main_module is lib/utf8/all.pm
Cannot decode string with wide characters at /Users/schwern/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/darwin-thread-multi-2level/Encode.pm line 175.
```

I'll spare you the gorey details, but that turned out to be in Dist::Zilla::Plugin::ReadmeAnyFromPod. I was using 0.150250. Upgrading to 0.161170 fixed it.

Since I'd also just upgraded Dist::Zilla to v6, it may have been this:

```
0.161150  2016-04-24 10:10:10-07:00 America/Los_Angeles
    - Update for Dist::Zilla v6 compatibility.
```

**Comment by HayoBaan** [comment]
Dist::Zilla v6 indeed caused some required updates (for me it was something in the 6.05 specifically that required a code change). The problem here is that the older Dist::Zilla::Plugin::ReadmeAnyFromPod is fine for when you still have Dist::Zilla < v6 so I can't require this newer version. At least, there is no way to specify versions conditionally, is there?

**Comment by schwern** [comment]
I don't know. If the 5/6 transition caused problems, it might be simplest to require Dist::Zilla 6.

**Comment by HayoBaan** [comment]
> If the 5/6 transition caused problems, it might be simplest to require Dist::Zilla 6.

Hmm, I'm a bit reluctant to do that as that might require people to upgrade while they don't really want to.

**Comment by HayoBaan** [comment]
As “final” solution I decided to simply require version 0.161150 of ReadmeAnyFromPod.
